location /api/init.php {
    limit_except POST { deny all; }
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root/api/init.php;
    fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
}