<script setup lang="ts">
import { computed } from "vue"
import { generateSchema } from "../schema";
import { useSeo } from "../composables/useSeo";
import { siteConfig } from "../site.config";
import { t } from "../i18n";
import { articles } from "../generated/articles";

const topArticles = computed(() => articles.slice(0, 3).map(a => ({
  slug: a.frontmatter.slug,
  title: a.frontmatter.title,
  desc: a.frontmatter.description,
  date: new Date(a.frontmatter.date).toLocaleDateString("ru-RU", { day: "numeric", month: "long" }),
  readTime: `${(a as any).readingTime || 5} min`,
  category: a.frontmatter.category,
  image: (a.frontmatter as any).image || "https://pixinlink.ru/api/v1/800x450/seo-schema-structured-data",
})))

useSeo({
  title: siteConfig.name,
  description: siteConfig.description,
  path: "/home/2/",
  type: "website",
  jsonLd: generateSchema({ url: siteConfig.url, path: "/home/2/", title: siteConfig.name, description: siteConfig.description, html: "", type: "website" }),
});
</script>

<template>
<main>
<div class="position-relative overflow-hidden" style="min-height:600px;background:linear-gradient(135deg,#1a0a2e,#3b0764)"><img src="https://pixinlink.ru/api/v1/1440x800/abstract-geometric-nodes-network-purple-dark-technology-grid" alt="" class="position-absolute top-0 start-0 w-100 h-100" style="object-fit:cover;opacity:0.12"><div class="container position-relative py-5" style="z-index:2"><div class="row align-items-center" style="min-height:500px"><div class="col-lg-7 text-white py-5"><p class="text-uppercase fw-bold mb-2 opacity-75" style="font-size:13px;letter-spacing:3px;color:#a78bfa">{{ t.homeVariant2.badge }}</p><h1 class="fw-bold mb-3 lh-sm" style="font-size:44px">{{ t.homeVariant2.heroText }}</h1><p class="lead mb-4 opacity-90" style="max-width:560px;font-size:18px">{{ t.homeVariant2.heroDesc }}</p><div class="d-flex flex-wrap gap-3"><a href="https://github.com/hubcms-dot/githubcms" class="btn btn-primary btn-lg px-4 py-3 fw-bold" style="border-radius:12px">{{ t.homeVariant2.ctaStart }}</a><a href="/blog/" class="btn btn-outline-light btn-lg px-4 py-3" style="border-radius:12px">{{ t.homeVariant2.ctaBlogs }}</a></div></div><div class="col-lg-5"><div class="d-flex flex-column gap-3"><div class="d-flex gap-3"><div class="flex-fill rounded-4 p-4 text-center text-white" style="background:rgba(255,255,255,0.08);backdrop-filter:blur(8px)"><div class="fw-bold mb-1" style="font-size:36px;color:#c4b5fd">≤200ms</div><div class="small opacity-75">{{ t.homeVariant2.statTtfb }}</div></div><div class="flex-fill rounded-4 p-4 text-center text-white" style="background:rgba(255,255,255,0.08);backdrop-filter:blur(8px)"><div class="fw-bold mb-1" style="font-size:36px;color:#c4b5fd">0</div><div class="small opacity-75">{{ t.homeVariant2.statDb }}</div></div></div><div class="rounded-4 p-4 text-center text-white" style="background:rgba(255,255,255,0.08);backdrop-filter:blur(8px)"><div class="fw-bold mb-1" style="font-size:36px;color:#c4b5fd">30–45%</div><div class="small opacity-75">{{ t.homeVariant2.statAi }}</div></div><div class="rounded-4 p-4 text-center text-white" style="background:rgba(255,255,255,0.08);backdrop-filter:blur(8px)"><div class="fw-bold mb-1" style="font-size:36px;color:#c4b5fd">10+</div><div class="small opacity-75">{{ t.homeVariant2.statSchema }}</div></div></div></div></div></div></div>

<section class="py-5"><div class="container"><div class="row text-center mb-5"><div class="col-lg-8 mx-auto"><h2 class="fw-bold mb-3" style="font-size:32px">{{ t.homeVariant2.section1Title }}</h2><p class="text-muted" style="font-size:16px">{{ t.homeVariant2.section1Desc }}</p></div></div><div class="row g-4"><div class="col-md-6 col-lg-3"><div class="card border-0 shadow-sm h-100 p-4 text-center" style="border-radius:14px"><div class="rounded-circle d-inline-flex align-items-center justify-content-center mx-auto mb-3" style="width:80px;height:80px;background:rgba(124,58,237,0.1)"><span style="font-size:32px">📝</span></div><h5 class="fw-bold mb-3" style="font-size:18px">{{ t.homeVariant2.card1Title }}</h5><p class="text-muted small mb-0" style="font-size:14px">{{ t.homeVariant2.card1Desc }}</p></div></div><div class="col-md-6 col-lg-3"><div class="card border-0 shadow-sm h-100 p-4 text-center" style="border-radius:14px"><div class="rounded-circle d-inline-flex align-items-center justify-content-center mx-auto mb-3" style="width:80px;height:80px;background:rgba(25,135,84,0.1)"><span style="font-size:32px">🤖</span></div><h5 class="fw-bold mb-3" style="font-size:18px">{{ t.homeVariant2.card2Title }}</h5><p class="text-muted small mb-0" style="font-size:14px">{{ t.homeVariant2.card2Desc }}</p></div></div><div class="col-md-6 col-lg-3"><div class="card border-0 shadow-sm h-100 p-4 text-center" style="border-radius:14px"><div class="rounded-circle d-inline-flex align-items-center justify-content-center mx-auto mb-3" style="width:80px;height:80px;background:rgba(255,193,7,0.15)"><span style="font-size:32px">⚡</span></div><h5 class="fw-bold mb-3" style="font-size:18px">{{ t.homeVariant2.card3Title }}</h5><p class="text-muted small mb-0" style="font-size:14px">{{ t.homeVariant2.card3Desc }}</p></div></div><div class="col-md-6 col-lg-3"><div class="card border-0 shadow-sm h-100 p-4 text-center" style="border-radius:14px"><div class="rounded-circle d-inline-flex align-items-center justify-content-center mx-auto mb-3" style="width:80px;height:80px;background:rgba(220,53,69,0.1)"><span style="font-size:32px">🗄️</span></div><h5 class="fw-bold mb-3" style="font-size:18px">{{ t.homeVariant2.card4Title }}</h5><p class="text-muted small mb-0" style="font-size:14px">{{ t.homeVariant2.card4Desc }}</p></div></div></div></div></section>

<section class="py-5 bg-light"><div class="container"><div class="row align-items-center"><div class="col-lg-6 mb-4 mb-lg-0"><img src="https://pixinlink.ru/api/v1/600x450/code-editor-markdown-files-static-site-generator-dark-minimal" alt="" class="img-fluid rounded-4 shadow" style="width:100%;height:420px;object-fit:cover"></div><div class="col-lg-6 ps-lg-5"><h2 class="fw-bold mb-4" style="font-size:32px">{{ t.homeVariant2.section2Title }}</h2><div class="d-flex mb-4"><div class="me-3 flex-shrink-0"><div class="rounded-circle d-flex align-items-center justify-content-center text-white fw-bold" style="width:44px;height:44px;font-size:18px;background:#7c3aed">1</div></div><div><p class="mb-0" style="font-size:16px">{{ t.homeVariant2.point1 }}</p></div></div><div class="d-flex mb-4"><div class="me-3 flex-shrink-0"><div class="rounded-circle d-flex align-items-center justify-content-center text-white fw-bold" style="width:44px;height:44px;font-size:18px;background:#7c3aed">2</div></div><div><p class="mb-0" style="font-size:16px">{{ t.homeVariant2.point2 }}</p></div></div><div class="d-flex"><div class="me-3 flex-shrink-0"><div class="rounded-circle d-flex align-items-center justify-content-center text-white fw-bold" style="width:44px;height:44px;font-size:18px;background:#7c3aed">3</div></div><div><p class="mb-0" style="font-size:16px">{{ t.homeVariant2.point3 }}</p></div></div><div style="border:1px solid #dee2e6;border-radius:14px;overflow:hidden;margin-top:16px"><table class="table table-striped mb-0"><thead style="background:rgba(124,58,237,0.06)"><tr><th style="color:#7c3aed">{{ t.homeVariant2.cmpParam }}</th><th style="color:#6c757d">{{ t.homeVariant2.cmpWp }}</th><th style="color:#7c3aed">{{ t.homeVariant2.cmpCms }}</th></tr></thead><tbody><tr><td>{{ t.homeVariant2.cmpRowTtfb }}</td><td>{{ t.homeVariant2.cmpRowTtfbWp }}</td><td>{{ t.homeVariant2.cmpRowTtfbCms }}</td></tr><tr><td>{{ t.homeVariant2.cmpRowJsonLd }}</td><td>{{ t.homeVariant2.cmpRowJsonLdWp }}</td><td>{{ t.homeVariant2.cmpRowJsonLdCms }}</td></tr><tr><td>{{ t.homeVariant2.cmpRowCost }}</td><td>{{ t.homeVariant2.cmpRowCostWp }}</td><td>{{ t.homeVariant2.cmpRowCostCms }}</td></tr><tr><td>{{ t.homeVariant2.cmpRowAi }}</td><td>{{ t.homeVariant2.cmpRowAiWp }}</td><td>{{ t.homeVariant2.cmpRowAiCms }}</td></tr></tbody></table></div></div></div></div></section>

<section class="py-5" style="background:linear-gradient(135deg,#7c3aed,#6d28d9)"><div class="container"><div class="row text-center text-white g-4"><div class="col-6 col-md-3"><div class="fw-bold mb-1" style="font-size:44px">30–45%</div><div class="opacity-75 small text-uppercase" style="letter-spacing:1px">{{ t.homeVariant2.stat1Label }}</div></div><div class="col-6 col-md-3"><div class="fw-bold mb-1" style="font-size:44px">≤200ms</div><div class="opacity-75 small text-uppercase" style="letter-spacing:1px">{{ t.homeVariant2.stat2Label }}</div></div><div class="col-6 col-md-3"><div class="fw-bold mb-1" style="font-size:44px">52</div><div class="opacity-75 small text-uppercase" style="letter-spacing:1px">{{ t.homeVariant2.stat3Label }}</div></div><div class="col-6 col-md-3"><div class="fw-bold mb-1" style="font-size:44px">$40</div><div class="opacity-75 small text-uppercase" style="letter-spacing:1px">{{ t.homeVariant2.stat4Label }}</div></div></div></div></section>

<section class="py-5"><div class="container"><div class="d-flex justify-content-between align-items-center mb-5"><h2 class="fw-bold mb-0" style="font-size:32px">{{ t.homeVariant2.blogSectionTitle }}</h2><a href="/blog/" class="btn btn-outline-primary" style="border-radius:10px">{{ t.homeVariant2.blogSectionAll }}</a></div><div class="row g-4">
  <div v-for="a in topArticles" :key="a.slug" class="col-md-4"><article class="card border-0 shadow-sm h-100 overflow-hidden" style="border-radius:14px"><img :src="a.image" class="card-img-top" alt="" style="height:200px;object-fit:cover"><div class="card-body d-flex flex-column p-4"><div class="mb-2"><span class="badge" style="background:rgba(124,58,237,0.1);color:#7c3aed;font-size:12px">{{ a.category }}</span></div><h5 class="fw-bold mb-2" style="font-size:17px">{{ a.title }}</h5><p class="text-muted small flex-grow-1" style="font-size:13px">{{ a.desc }}</p><div class="d-flex justify-content-between align-items-center mt-3"><small class="text-muted">{{ a.date }} · {{ a.readTime }}</small><RouterLink :to="'/blog/' + a.slug + '/'" class="btn btn-sm btn-outline-primary" style="border-radius:8px">{{ t.homeVariant2.blogSectionAll.replace(' →',' →') }}</RouterLink></div></div></article></div>
</div></div></section>

<section class="py-5 text-center text-white" style="background:linear-gradient(135deg,#1a0a2e,#2d1060);border-radius:0"><div class="container py-4"><h2 class="fw-bold mb-3" style="font-size:36px">{{ t.homeVariant2.ctaTitle }}</h2><p class="lead mb-4 opacity-85 mx-auto" style="max-width:600px;font-size:18px">{{ t.homeVariant2.ctaDesc }}</p><div class="d-flex justify-content-center flex-wrap gap-3"><a href="https://github.com/hubcms-dot/githubcms" class="btn btn-light btn-lg px-5 py-3 fw-bold" style="border-radius:12px;color:#7c3aed">{{ t.homeVariant2.ctaClone }}</a><a href="/blog/deploy-vps-nginx-ssl/" class="btn btn-outline-light btn-lg px-5 py-3" style="border-radius:12px">{{ t.homeVariant2.ctaGuide }}</a></div><p class="mt-3 small opacity-50">{{ t.homeVariant2.ctaLicense }}</p></div></section>
</main>
</template>

<style scoped>
</style>
