<script setup lang="ts">
import { computed } from "vue"
import { useSeo } from "../composables/useSeo"
import { siteConfig } from "../site.config"
import BreadcrumbNav from "../components/BreadcrumbNav.vue"

const props = defineProps<{ slug: string }>()

interface Tpl { name: string; slug: string; price: string; desc: string; longDesc: string; preview: string; features: string[]; faq: { q: string; a: string }[] }

const freeTemplates: Record<string, Tpl> = {
  "purple-geo-lite": { name:"Purple GEO Lite", slug:"purple-geo-lite", price:"Бесплатно", desc:"Обрезанный Free-шаблон GitHub CMS с фиолетовой визуальной системой.", longDesc:"Базовый Free-шаблон GitHub CMS. Он включает один дизайн, одну главную страницу, базовые SEO-промпты и статическую Vue/Vite SSG-сборку. Смена шаблонов, расширенные GEO-промпты и marketplace относятся к Pro.", preview:"https://pixinlink.ru/api/v1/800x500/purple-geo-lite-static-site-template", features:["Один установленный дизайн","Базовые SEO-промпты","Vue/Vite SSG","Bootstrap 5","Без смены шаблонов","Без Pro GEO-блоков"], faq:[{q:"Это единственный шаблон Free?",a:"Да. Free-дистрибутив включает только Purple GEO Lite."},{q:"Можно сменить шаблон?",a:"Смена шаблонов и marketplace доступны в Pro."},{q:"Что входит?",a:"Тема, базовый prompt-pack и статическая сборка без backend."}] },
}

const proTemplates: Record<string, Tpl> = import.meta.env.VITE_EDITION === "pro" ? {
  "purple-geo": { name:"Purple GEO", slug:"purple-geo", price:"3 500 ₽", desc:"Мощный GEO-оптимизированный дизайн с фиолетовой гаммой.", longDesc:"Флагманский шаблон для коммерческих сайтов. 628 строк CSS, Plob-стилистика (градиенты, тени), 24-блочный GEO-промпт, персональные промпты и Bootstrap 5.", preview:"https://pixinlink.ru/api/v1/800x500/modern-purple-geo-template", features:["Полный CSS (628 строк)","Адаптивная тёмная тема","Plob-стилистика","24-блочный GEO-промпт","Персональные промпты","Bootstrap 5 + печать"], faq:[{q:"Для каких сайтов?",a:"Коммерческие сайты и B2B-лендинги."},{q:"Обновления?",a:"Пожизненные обновления включены."},{q:"Чем отличается от бесплатного?",a:"628 строк CSS и GEO-промпты."}] },
  "tech-azure": { name:"Tech Azure", slug:"tech-azure", price:"3 500 ₽", desc:"Лазурный технологичный дизайн для SaaS и IT-компаний.", longDesc:"Стеклянные карточки, лазурная гамма, градиенты. Идеален для SaaS-лендингов и IT-продуктов.", preview:"https://pixinlink.ru/api/v1/800x500/azure-tech-saas-template", features:["Стеклянные карточки","Лазурная гамма","SaaS-лендинги","Тёмная тема","Bootstrap 5"], faq:[{q:"Для чего?",a:"SaaS и IT-продукты."},{q:"Стеклянные карточки?",a:"Да, backdrop-filter эффекты."}] },
  "emerald-green": { name:"Emerald Green", slug:"emerald-green", price:"3 500 ₽", desc:"Изумрудный дизайн для экологических и wellness-проектов.", longDesc:"Природные оттенки, мягкие тени. Для eco-брендов и wellness.", preview:"https://pixinlink.ru/api/v1/800x500/emerald-green-eco-template", features:["Природная гамма","Мягкие тени","Eco-стиль","Тёмная тема"], faq:[{q:"Для кого?",a:"Eco-бренды и wellness."}] },
  "crimson-bold": { name:"Crimson Bold", slug:"crimson-bold", price:"3 500 ₽", desc:"Яркий смелый дизайн для медиа и развлечений.", longDesc:"Красные акценты, крупная типографика. Для СМИ и развлечений.", preview:"https://pixinlink.ru/api/v1/800x500/crimson-bold-media-template", features:["Крупная типографика","Красные акценты","Медиа-стиль"], faq:[{q:"Для медиа?",a:"Да, СМИ и развлечения."}] },
  "amber-warm": { name:"Amber Warm", slug:"amber-warm", price:"3 500 ₽", desc:"Тёплый янтарный дизайн для образования и блогов.", longDesc:"Уютная цветовая гамма, карточки с тенями. Для курсов и блогов.", preview:"https://pixinlink.ru/api/v1/800x500/amber-warm-education-blog-template", features:["Тёплая гамма","Карточки с тенями","Образовательный стиль"], faq:[{q:"Для блогов?",a:"Да, идеально для образовательных блогов."}] },
  "indigo-deep": { name:"Indigo Deep", slug:"indigo-deep", price:"3 500 ₽", desc:"Глубокий индиго для финансовых и юридических сайтов.", longDesc:"Строгий профессиональный дизайн. Для банков и юристов.", preview:"https://pixinlink.ru/api/v1/800x500/indigo-deep-finance-legal-template", features:["Строгий дизайн","Индиго-гамма","Финансовый стиль","Тёмная тема"], faq:[{q:"Для юрлиц?",a:"Да, банки и юридические компании."}] },
  "rose-elegant": { name:"Rose Elegant", slug:"rose-elegant", price:"3 500 ₽", desc:"Элегантный розовый дизайн для бьюти-брендов и fashion.", longDesc:"Элегантная типографика, розовая гамма. Для beauty и fashion.", preview:"https://pixinlink.ru/api/v1/800x500/rose-elegant-fashion-template", features:["Элегантная типографика","Розовая гамма","Fashion-стиль","Лёгкие тени"], faq:[{q:"Для fashion?",a:"Да, бьюти-бренды и мода."}] },
  "ocean-breeze": { name:"Ocean Breeze", slug:"ocean-breeze", price:"3 500 ₽", desc:"Свежий морской дизайн для туристических проектов.", longDesc:"Морская палитра, воздушные карточки. Для travel и туризма.", preview:"https://pixinlink.ru/api/v1/800x500/ocean-breeze-travel-template", features:["Морская палитра","Travel-стиль","Воздушные карточки"], faq:[{q:"Для туризма?",a:"Да, турфирмы и тревел-блоги."}] },
  "sunset-orange": { name:"Sunset Orange", slug:"sunset-orange", price:"3 500 ₽", desc:"Энергичный оранжевый дизайн для спорта и фитнеса.", longDesc:"Энергичный стиль, оранжевая гамма. Для спортзалов и фитнеса.", preview:"https://pixinlink.ru/api/v1/800x500/sunset-orange-sports-template", features:["Энергичный стиль","Оранжевая гамма","Fitness-карточки"], faq:[{q:"Для фитнеса?",a:"Да, спортзалы и фитнес-клубы."}] },
  "midnight-noir": { name:"Midnight Noir", slug:"midnight-noir", price:"3 500 ₽", desc:"Тёмный минималистичный дизайн для портфолио.", longDesc:"Полностью тёмная тема, монохром. Для креативных студий.", preview:"https://pixinlink.ru/api/v1/800x500/midnight-noir-portfolio-template", features:["Полностью тёмная тема","Минимализм","Портфолио-сетка"], faq:[{q:"Только тёмная?",a:"Да, монохромный тёмный дизайн."}] },
  "spring-garden": { name:"Spring Garden", slug:"spring-garden", price:"3 500 ₽", desc:"Весенний дизайн для садоводства и флористики.", longDesc:"Светлая палитра, цветочные акценты. Для садов и семейных проектов.", preview:"https://pixinlink.ru/api/v1/800x500/spring-garden-floral-template", features:["Светлая палитра","Цветочные акценты","Семейный стиль"], faq:[{q:"Для садоводов?",a:"Да, флористика и садоводство."}] },
  "arctic-frost": { name:"Arctic Frost", slug:"arctic-frost", price:"3 500 ₽", desc:"Ледяной минималистичный дизайн для стартапов.", longDesc:"Ледяная палитра, стеклянные элементы. Для технологичных стартапов.", preview:"https://pixinlink.ru/api/v1/800x500/arctic-frost-startup-template", features:["Ледяная палитра","Минимализм","Техно-стиль"], faq:[{q:"Для стартапов?",a:"Да, технологические компании."}] },
  "golden-hour": { name:"Golden Hour", slug:"golden-hour", price:"3 500 ₽", desc:"Золотистый премиум-дизайн для люксовых брендов.", longDesc:"Золотая палитра, элегантные шрифты. Для ювелирных магазинов.", preview:"https://pixinlink.ru/api/v1/800x500/golden-luxury-jewelry-template", features:["Золотая палитра","Премиум-стиль","Элегантные шрифты"], faq:[{q:"Для люкса?",a:"Да, ювелирные и люксовые бренды."}] },
  "cyber-neon": { name:"Cyber Neon", slug:"cyber-neon", price:"3 500 ₽", desc:"Киберпанк-неоновый дизайн для игр и Web3.", longDesc:"Неоновая палитра, киберпанк-стиль. Для гейминга и Web3 проектов.", preview:"https://pixinlink.ru/api/v1/800x500/cyber-neon-gaming-template", features:["Неоновая палитра","Киберпанк-стиль","Тёмная тема"], faq:[{q:"Для игр?",a:"Да, гейминг и Web3 проекты."}] },
  "monaco-sky": { name:"Monaco Sky", slug:"monaco-sky", price:"3 500 ₽", desc:"Небесно-голубой дизайн для авиации и транспорта.", longDesc:"Небесная палитра, чистые линии. Для авиации и логистики.", preview:"https://pixinlink.ru/api/v1/800x500/sky-blue-aviation-template", features:["Небесная палитра","Авиа-стиль","Чистые линии"], faq:[{q:"Для авиации?",a:"Да, транспорт и логистика."}] },
  "velvet-night": { name:"Velvet Night", slug:"velvet-night", price:"3 500 ₽", desc:"Бархатный тёмный дизайн для ресторанов и баров.", longDesc:"Тёмная бархатная палитра, акцентные градиенты. Для HoReCa.", preview:"https://pixinlink.ru/api/v1/800x500/velvet-night-restaurant-template", features:["Тёмная бархатная палитра","Ресторанный стиль","Акцентные градиенты"], faq:[{q:"Для ресторанов?",a:"Да, бары и рестораны."}] },
  "forest-trail": { name:"Forest Trail", slug:"forest-trail", price:"3 500 ₽", desc:"Лесной дизайн для outdoor-брендов и кемпинга.", longDesc:"Лесная палитра, природные текстуры. Для активного отдыха.", preview:"https://pixinlink.ru/api/v1/800x500/forest-trail-outdoor-template", features:["Лесная палитра","Outdoor-стиль","Природные текстуры"], faq:[{q:"Для кемпинга?",a:"Да, outdoor и активный отдых."}] },
  "arctic-dusk": { name:"Arctic Dusk", slug:"arctic-dusk", price:"3 500 ₽", desc:"Арктический сумеречный дизайн для скандинавского стиля.", longDesc:"Сумеречная палитра, чистые линии. Для минималистичных проектов.", preview:"https://pixinlink.ru/api/v1/800x500/arctic-dusk-scandinavian-template", features:["Сумеречная палитра","Скандинавский стиль","Минимализм"], faq:[{q:"Скандинавский?",a:"Да, чистые линии и минимализм."}] },
  "coral-reef": { name:"Coral Reef", slug:"coral-reef", price:"3 500 ₽", desc:"Коралловый дизайн для детских и развлекательных проектов.", longDesc:"Коралловая палитра, крупные карточки. Для детей и праздников.", preview:"https://pixinlink.ru/api/v1/800x500/coral-reef-kids-template", features:["Коралловая палитра","Игровой стиль","Крупные карточки"], faq:[{q:"Для детей?",a:"Да, детские и развлекательные проекты."}] },
  "steel-grey": { name:"Steel Grey", slug:"steel-grey", price:"3 500 ₽", desc:"Стальной дизайн для B2B и промышленных компаний.", longDesc:"Стальная палитра, строгая типографика. Для заводов и B2B.", preview:"https://pixinlink.ru/api/v1/800x500/steel-grey-industrial-template", features:["Стальная палитра","Промышленный стиль","B2B-карточки"], faq:[{q:"Для B2B?",a:"Да, промышленность и производство."}] },
  "mint-fresh": { name:"Mint Fresh", slug:"mint-fresh", price:"3 500 ₽", desc:"Свежий мятный дизайн для медицинских проектов.", longDesc:"Мятная палитра, чистый дизайн. Для клиник и health-tech.", preview:"https://pixinlink.ru/api/v1/800x500/mint-fresh-medical-template", features:["Мятная палитра","Медицинский стиль","Чистый дизайн"], faq:[{q:"Для медицины?",a:"Да, клиники и health-tech."}] },
  "chocolate-luxe": { name:"Chocolate Luxe", slug:"chocolate-luxe", price:"3 500 ₽", desc:"Шоколадный премиум-дизайн для кондитерских и кофеен.", longDesc:"Шоколадная палитра, тёплые оттенки. Для пекарен и кафе.", preview:"https://pixinlink.ru/api/v1/800x500/chocolate-luxe-bakery-template", features:["Шоколадная палитра","Премиум-стиль","Тёплые оттенки"], faq:[{q:"Для кофеен?",a:"Да, кондитерские и пекарни."}] },
  "graphite-mono": { name:"Graphite Mono", slug:"graphite-mono", price:"3 500 ₽", desc:"Графитовый монохром для архитектурных бюро.", longDesc:"Монохромная палитра, сетка портфолио. Для архитекторов.", preview:"https://pixinlink.ru/api/v1/800x500/graphite-mono-architecture-template", features:["Монохромная палитра","Архитектурный стиль","Сетка портфолио"], faq:[{q:"Для архитекторов?",a:"Да, бюро и дизайн-студии."}] },
  "sakura-pink": { name:"Sakura Pink", slug:"sakura-pink", price:"3 500 ₽", desc:"Нежно-розовый дизайн в японском стиле.", longDesc:"Сакура-палитра, нежные акценты. Для творческих проектов.", preview:"https://pixinlink.ru/api/v1/800x500/sakura-pink-japanese-template", features:["Сакура-палитра","Японский стиль","Нежные акценты"], faq:[{q:"Японский стиль?",a:"Да, сакура и минимализм."}] },
  "violet-dusk": { name:"Violet Dusk", slug:"violet-dusk", price:"3 500 ₽", desc:"Фиолетовый сумеречный дизайн для духовных проектов.", longDesc:"Фиолетовая палитра, градиенты. Для эзотерики и творчества.", preview:"https://pixinlink.ru/api/v1/800x500/violet-dusk-mystical-template", features:["Фиолетовая палитра","Мистический стиль","Градиенты"], faq:[{q:"Для духовных?",a:"Да, эзотерика и творчество."}] },
  "lemon-zest": { name:"Lemon Zest", slug:"lemon-zest", price:"3 500 ₽", desc:"Яркий лимонный дизайн для стартапов и агентств.", longDesc:"Лимонная палитра, энергичные акценты. Для креативных команд.", preview:"https://pixinlink.ru/api/v1/800x500/lemon-zest-creative-template", features:["Лимонная палитра","Стартап-стиль","Энергичные акценты"], faq:[{q:"Для стартапов?",a:"Да, креативные агентства и стартапы."}] },
  "storm-cloud": { name:"Storm Cloud", slug:"storm-cloud", price:"3 500 ₽", desc:"Грозовой дизайн для погодных и новостных проектов.", longDesc:"Облачная палитра, динамичные карточки. Для СМИ и метео.", preview:"https://pixinlink.ru/api/v1/800x500/storm-cloud-news-template", features:["Облачная палитра","Новостной стиль","Динамичные карточки"], faq:[{q:"Для новостей?",a:"Да, новостные и погодные проекты."}] },
  "peach-blossom": { name:"Peach Blossom", slug:"peach-blossom", price:"3 500 ₽", desc:"Персиковый нежный дизайн для свадебных проектов.", longDesc:"Персиковая палитра, элегантная типографика. Для свадеб.", preview:"https://pixinlink.ru/api/v1/800x500/peach-blossom-wedding-template", features:["Персиковая палитра","Свадебный стиль","Элегантная типографика"], faq:[{q:"Для свадеб?",a:"Да, свадебные и event-агентства."}] },
  "deep-ocean": { name:"Deep Ocean", slug:"deep-ocean", price:"3 500 ₽", desc:"Глубоководный дизайн для морских и научных проектов.", longDesc:"Океанская палитра, глубокие оттенки. Для науки и дайвинга.", preview:"https://pixinlink.ru/api/v1/800x500/deep-ocean-marine-template", features:["Океанская палитра","Морской стиль","Глубокие оттенки"], faq:[{q:"Для науки?",a:"Да, морские исследования и дайвинг."}] },
} : {}
const templates: Record<string, Tpl> = { ...freeTemplates, ...proTemplates }

const tpl = computed(() => templates[props.slug])

useSeo(() => {
  const t = tpl.value
  if (!t) return { title: siteConfig.name, description: siteConfig.description, path: "/templates/", type: "website" }
  return { title: t.name + " — " + t.price + " | " + siteConfig.name, description: t.desc, path: "/templates/" + t.slug + "/", type: "website", image: t.preview }
})
</script>

<template>
  <main v-if="!tpl" class="py-5 text-center"><h2>Шаблон не найден</h2></main>
  <main v-else>
    <BreadcrumbNav :items="[{ name: 'Главная', url: '/' }, { name: 'Шаблоны', url: '/templates/' }, { name: tpl.name }]" />
    <section class="position-relative overflow-hidden" style="min-height:400px;background:linear-gradient(135deg,#0a0414,#1a0a2e,#2d1060)"><div class="container position-relative py-5" style="z-index:2"><div class="row align-items-center"><div class="col-lg-7 text-white"><p class="text-uppercase fw-bold mb-2 opacity-75" style="font-size:12px;letter-spacing:3px;color:#c4b5fd">ШАБЛОН</p><h1 class="fw-bold mb-3 lh-sm" style="font-size:36px">{{ tpl.name }}</h1><p class="lead mb-4 opacity-85" style="font-size:17px">{{ tpl.desc }}</p><div class="d-flex align-items-center gap-3 mb-3"><span class="fw-bold" style="font-size:32px;color:#c4b5fd">{{ tpl.price }}</span></div><a v-if="tpl.price === 'Бесплатно'" href="#" class="btn btn-light btn-lg px-5 py-3 fw-bold" style="border-radius:12px;color:var(--color-accent)">Установить</a><button v-else class="btn btn-light btn-lg px-5 py-3 fw-bold" style="border-radius:12px;color:var(--color-accent)" @click="alert('Платёжная система настраивается')">Купить — {{ tpl.price }} →</button></div><div class="col-lg-5 text-center mt-4 mt-lg-0"><img :src="tpl.preview" :alt="tpl.name" class="img-fluid rounded-4" style="box-shadow:0 20px 60px rgba(0,0,0,0.5)"></div></div></div></section>
    <section class="py-5"><div class="container"><h2 class="fw-bold mb-4" style="font-size:28px">Описание</h2><p style="font-size:15px;line-height:1.8;color:var(--color-text-muted);max-width:800px">{{ tpl.longDesc }}</p></div></section>
    <section class="py-5" style="background:var(--color-bg-muted)"><div class="container"><h2 class="fw-bold mb-4" style="font-size:28px">Что включено</h2><div class="row g-3"><div v-for="(f, i) in tpl.features" :key="i" class="col-sm-6 col-lg-4"><div class="d-flex"><span class="fw-bold me-2" style="color:var(--color-accent)">✓</span><span style="font-size:14px">{{ f }}</span></div></div></div></div></section>
    <section class="py-5"><div class="container"><h2 class="fw-bold mb-4" style="font-size:28px">Вопросы</h2><div class="row g-4"><div v-for="(f, i) in tpl.faq" :key="i" class="col-md-4"><div class="card border-0 shadow-sm h-100 p-4" style="border-radius:14px"><h5 class="fw-bold mb-2" style="font-size:14px;color:var(--color-accent)">{{ f.q }}</h5><p class="mb-0" style="font-size:13px;color:var(--color-text-muted)">{{ f.a }}</p></div></div></div></div></section>
    <section class="py-5 text-center text-white" style="background:linear-gradient(135deg,#0a0414,#1a0a2e,#2d1060)"><div class="container py-4"><h2 class="fw-bold mb-3" style="font-size:30px">{{ tpl.name }} — {{ tpl.price }}</h2><p class="mb-4 opacity-85">Установка одной командой. Пожизненные обновления.</p><a v-if="tpl.price === 'Бесплатно'" href="#" class="btn btn-light btn-lg px-5 py-3 fw-bold" style="border-radius:12px;color:var(--color-accent)">Установить</a><button v-else class="btn btn-light btn-lg px-5 py-3 fw-bold" style="border-radius:12px;color:var(--color-accent)" @click="alert('Платёжная система настраивается')">Купить — {{ tpl.price }} →</button></div></section>
  </main>
</template>
