import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import MarkdownIt from "markdown-it";
import sanitizeHtml from "sanitize-html";
import hljs from "highlight.js";
import { sanitizerOptions } from "./sanitize-config.mjs";
import { slugify } from "./shared/slugify.mjs";

const outputDir = join(process.cwd(), "src", "generated");

const markdown = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
  highlight(str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(str, { language: lang }).value;
      } catch {}
    }
    // Return escaped source instead of empty string for unknown languages
    return markdown.utils.escapeHtml(str);
  },
});

function normalizeStringArray(value) {
  return Array.isArray(value) ? value.map(String) : [];
}

function extractBlocks(rawContent) {
  const blocks = {};
  const markerRegex = /<!--\s*@block:\s*(\S+)\s*-->/g;
  const parts = rawContent.split(markerRegex);
  for (let i = 1; i < parts.length; i += 2) {
    const name = parts[i];
    const content = (parts[i + 1] ?? "").trim();
    if (!content) {
      blocks[name] = "";
      continue;
    }
    const rendered = markdown.render(content);
    blocks[name] = sanitizeHtml(rendered, sanitizerOptions);
  }
  return blocks;
}

function extractFaq(body, blocks) {
  const hasFaq = blocks.faq || body.match(/###?\s*FAQ/i) || body.match(/<!--\s*@block:\s*faq\s*-->/i);
  if (!hasFaq) return [];

  const items = [];
  const qaRegex = /\*\*Q:\s*(.+?)\*\*\s*([\s\S]*?)(?=\*\*Q:\s*|$)/gi;
  let match;

  while ((match = qaRegex.exec(body)) !== null) {
    items.push({
      question: match[1].trim(),
      answer: match[2].replace(/^\s*\*\*A:\s*\*\*?\s*/i, "").trim(),
    });
  }

  return items;
}

const markdownCache = new Map();

function toContentFile(baseDir, file) {
  const relativePath = `${baseDir}/${file}`;
  const source = readFileSync(join(process.cwd(), relativePath), "utf8");
  const parsed = matter(source);
  const frontmatter = parsed.data;
  const slug = String(frontmatter.slug || slugify(frontmatter.title || file.replace(/\.md$/, ""))).trim();

  const blocks = extractBlocks(parsed.content);
  const faqItems = extractFaq(parsed.content, blocks);
  const bodyWithoutBlocks = parsed.content.replace(/<!--\s*@block:\s*\S+\s*-->/g, "");

  // Simple cache for markdown rendering (fast path)
  const cacheKey = `${file}:${bodyWithoutBlocks.length}`;
  let html = markdownCache.get(cacheKey);
  if (!html) {
    const unsafeHtml = markdown.render(bodyWithoutBlocks);
    html = sanitizeHtml(unsafeHtml, sanitizerOptions);
    markdownCache.set(cacheKey, html);
    if (markdownCache.size > 500) markdownCache.clear(); // prevent memory leak
  }

  const wordCount = bodyWithoutBlocks.split(/\s+/).filter(Boolean).length;
  const readingTime = Math.max(1, Math.ceil(wordCount / 200));

  return {
    path: relativePath,
    frontmatter: {
      title: String(frontmatter.title ?? ""),
      description: String(frontmatter.description ?? ""),
      slug: slug,
      date: String(frontmatter.date ?? ""),
      updated: frontmatter.updated ? String(frontmatter.updated) : undefined,
      author: String(frontmatter.author ?? "GitHub CMS"),
      category: String(frontmatter.category ?? "General"),
      tags: normalizeStringArray(frontmatter.tags),
      schema_type: String(frontmatter.schema_type ?? "Article"),
      layout: String(frontmatter.layout ?? "article"),
      cover_image: frontmatter.cover_image ? String(frontmatter.cover_image) : undefined,
      geo: normalizeStringArray(frontmatter.geo),
    },
    html,
    blocks,
    faqItems,
    readingTime,
  };
}

function getLocale() {
  return process.env.VITE_LOCALE || "ru";
}

function generateContent(baseDir, outputFile, sortByDate = true) {
  const locale = getLocale();
  const localeBaseDir = `content/${locale}/${baseDir.replace(/^content\//, "")}`;
  const contentDir = join(process.cwd(), localeBaseDir);

  if (!existsSync(contentDir)) return 0;

  const files = readdirSync(contentDir).filter((f) => f.endsWith(".md"));
  const items = files.map((f) => toContentFile(localeBaseDir, f));

  if (sortByDate) {
    items.sort((a, b) => b.frontmatter.date.localeCompare(a.frontmatter.date));
  }

  const varName = baseDir === "content/blog" ? "articles" : "pages";

  writeFileSync(
    outputFile,
    `/* This file is generated by scripts/generate-content.mjs. */\n` +
      `export const ${varName} = ${JSON.stringify(items, null, 2)} as const;\n`,
    "utf8",
  );

  return items.length;
}

mkdirSync(outputDir, { recursive: true });

const articleCount = generateContent(
  "content/blog",
  join(outputDir, "articles.ts"),
  true,
);

const pageCount = generateContent(
  "content/pages",
  join(outputDir, "pages.ts"),
  false,
);

console.log(`Generated articles: ${articleCount}, pages: ${pageCount}.`);
